#!/usr/bin/perl
use strict;
use warnings;
use Getopt::Long;

# 定义sections与变量值之间的联动关系
my %config = (
    "a" => {
        var1 => "value_for_a_var1",
        var2 => "value_for_a_var2"
    },
    "b" => {
        var1 => "value_for_b_var1",
        var2 => "value_for_b_var2"
    }
);

# 获取命令行参数
my $section;
GetOptions("section=s" => \$section) or die "Error in command line arguments\n";

# 检查并设置变量
if (exists $config{$section}) {
    my $var1 = $config{$section}{var1};
    my $var2 = $config{$section}{var2};
    
    print "Selected section: $section\n";
    print "\$var1 = $var1\n";
    print "\$var2 = $var2\n";
} else {
    die "Invalid section: $section. Valid sections are: " . join(", ", keys %config) . "\n";
}
